include:
  - ./docker-compose.yaml

services:
  ollama:
    container_name: ollama-api
    build:
      context: ./ollama
      dockerfile: Dockerfile
    # image: ollama/ollama:0.5.7
    ports:
      - "11434:11434"
    expose:
      - "11434" # 他のコンテナから接続するため
    volumes:
      - ./volumes/ollama:/root/.ollama